### ISSUE TITLE
Allow overriding of the entire middleware

### ISSUE THREAD

**Issue by dsample** [TinyBlueRobots/Hornbill#15]
I'm trying to create an fake OpenID server to test against, and to do this I've had to avoid the `FakeService` inheritance that I'm used to. Because of this I'm having to start my own host, pick a port, etc.

What I'd like to be able to do is inherit from `FakeService` class and override all of the usual Hornbill middleware. I'd say this is similar to using `AddResponse`, but where the response is a more complex set of interactions.

For the OpenID provider I'm using `IdentityServer3`

```csharp
app.UseIdentityServer(new IdentityServerOptions {
  Factory = new IdentityServerServiceFactory()
    .UseInMemoryClients(clients)
    .UseInMemoryScopes(scopes)
    .UseInMemoryUsers(users),
  SigningCertificate = LoadCertificate(),
  RequireSsl = false
})
```

I'd just like to be able to pass `app` to FakeService to host.

**Comment by JonCanning** [comment]
Have just pushed `2.3.0`

**Comment by CraftyFella** [comment]
Glad to hear it's still being used...
